language: python
sudo: required
group: edge
addons:
  apt:
    packages:
      - python3-dev
python:
  - '3.6'
cache: pip
install:
  - pip3 install -r requirements.txt
before_script:
  - psql -c 'create database test;' -U postgres
  - export DATABASE_URL=postgresql://postgres@localhost:5432/test
  - export TEST_DATABASE_URL=postgresql://postgres@localhost:5432/test

script:
  - python -m pytest
