from docxtpl import DocxTemplate, RichText
tpl = DocxTemplate('../format.docx')
context = {
    'date':'13-05-2018',
    'room':'A102',
    'rows': [
        {'day': 'mon', 'slot1': {'name': 'DBMS',
                                 't_name': 'Aniket', 'batch': 'p1-cse(e)'},
         'slot2': {'name': 'DBMS',
                   't_name': 'Aniket', 'batch': 'p1-cse(e)'},
         'slot3': {'name': 'COA',
                   't_name': 'Aniket', 'batch': 'p1-cse(e)'},
         'slot4': {'name': 'MATHS',
                   't_name': 'Aniket', 'batch': 'p1-cse(e)'},
         'slot5': {'name': 'CS',
                   't_name': 'Aniket', 'batch': 'p1-cse(e)'},
            'slot6': {'name': 'DBMS',
                      't_name': 'Aniket', 'batch': 'p1-cse(e)'},
                'slot7': {'name': 'DBMS',
                          't_name': 'Aniket', 'batch': 'p1-cse(e)'},
         'slot8': {'name': 'DBMS',
                   't_name': 'Aniket', 'batch': 'p1-cse(e)'},

         },
        {'day': 'tue', 'slot1': {'name': 'DBMS',
                                 't_name': 'Aniket', 'batch': 'p1-cse(e)'},
         'slot2': {'name': 'DBMS',
                   't_name': 'Aniket', 'batch': 'p1-cse(e)'},
         'slot3': {'name': 'COA',
                   't_name': 'Aniket', 'batch': 'p1-cse(e)'},
         'slot4': {'name': 'MATHS',
                   't_name': 'Aniket', 'batch': 'p1-cse(e)'},
         'slot5': {'name': 'CS',
                   't_name': 'Aniket', 'batch': 'p1-cse(e)'},
            'slot6': {'name': 'DBMS',
                      't_name': 'Aniket', 'batch': 'p1-cse(e)'},
         'slot7': {'name': 'DBMS',
                   't_name': 'Aniket', 'batch': 'p1-cse(e)'},
         'slot8': {'name': 'DBMS',
                   't_name': 'Aniket', 'batch': 'p1-cse(e)'},

         },
        {'day': 'wed', 'slot1': {'name': 'DBMS',
                                 't_name': 'Aniket', 'batch': 'p1-cse(e)'},
         'slot2': {'name': 'DBMS',
                   't_name': 'Aniket', 'batch': 'p1-cse(e)'},
         'slot3': {'name': 'COA',
                   't_name': 'Aniket', 'batch': 'p1-cse(e)'},
         'slot4': {'name': 'MATHS',
                   't_name': 'Aniket', 'batch': 'p1-cse(e)'},
         'slot5': {'name': 'CS',
                   't_name': 'Aniket', 'batch': 'p1-cse(e)'},
            'slot6': {'name': 'DBMS',
                      't_name': 'Aniket', 'batch': 'p1-cse(e)'},
         'slot7': {'name': 'DBMS',
                   't_name': 'Aniket', 'batch': 'p1-cse(e)'},
         'slot8': {'name': 'DBMS',
                   't_name': 'Aniket', 'batch': 'p1-cse(e)'},

         },
        {'day': 'thu', 'slot1': {'name': 'DBMS',
                                 't_name': 'Aniket', 'batch': 'p1-cse(e)'},
         'slot2': {'name': 'DBMS',
                   't_name': 'Aniket', 'batch': 'p1-cse(e)'},
         'slot3': {'name': 'COA',
                   't_name': 'Aniket', 'batch': 'p1-cse(e)'},
         'slot4': {'name': 'MATHS',
                   't_name': 'Aniket', 'batch': 'p1-cse(e)'},
         'slot5': {'name': 'CS',
                   't_name': 'Aniket', 'batch': 'p1-cse(e)'},
            'slot6': {'name': 'DBMS',
                      't_name': 'Aniket', 'batch': 'p1-cse(e)'},
         'slot7': {'name': 'DBMS',
                   't_name': 'Aniket', 'batch': 'p1-cse(e)'},
         'slot8': {'name': 'DBMS',
                   't_name': 'Aniket', 'batch': 'p1-cse(e)'},

         },
        {'day': 'fri', 'slot1': {'name': 'DBMS',
                                 't_name': 'Aniket', 'batch': 'p1-cse(e)'},
         'slot2': {'name': 'DBMS',
                   't_name': 'Aniket', 'batch': 'p1-cse(e)'},
         'slot3': {'name': 'COA',
                   't_name': 'Aniket', 'batch': 'p1-cse(e)'},
         'slot4': {'name': 'MATHS',
                   't_name': 'Aniket', 'batch': 'p1-cse(e)'},
         'slot5': {'name': 'CS',
                   't_name': 'Aniket', 'batch': 'p1-cse(e)'},
            'slot6': {'name': 'DBMS',
                      't_name': 'Aniket', 'batch': 'p1-cse(e)'},
         'slot7': {'name': 'DBMS',
                   't_name': 'Aniket', 'batch': 'p1-cse(e)'},
         'slot8': {'name': 'DBMS',
                   't_name': 'Aniket', 'batch': 'p1-cse(e)'},

         },


    ],
}

tpl.render(context)
tpl.save('test.docx')
